name: flutter_quote_generator_v2
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  widgetbook: ^3.10.0
  widgetbook_annotation: ^3.2.0
  go_router: ^14.6.1
  font_awesome_flutter: ^10.8.0
  intl: ^0.19.0
  equatable: ^2.0.7
  hive_flutter: ^1.1.0
  get_it: ^8.0.2
  injectable: ^2.5.0
  path: ^1.9.0
  path_provider: ^2.1.5
  flutter_secure_storage: ^4.2.1
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  ua_client_hints: ^1.4.0
  fpdart: ^1.1.1
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  flutter_card_swiper: ^7.0.2
  carousel_slider: ^5.0.0
  collection: ^1.18.0
  import_sorter: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  widgetbook_generator: ^3.9.0
  injectable_generator: ^2.6.2
  flutter_gen_runner:
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: ibmPlexSansThai
      fonts:
        - asset: assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Thin.ttf
          weight: 100
        - asset: assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Light.ttf
          weight: 300
        - asset: assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Regular.ttf
          weight: 400
        - asset: assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Medium.ttf
          weight: 500
        - asset: assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Bold.ttf
          weight: 700

flutter_gen:
  output: ./lib/core/generated
  line_length: 80
  integrations:
    flutter_svg: false
    flare_flutter: false
    rive: false
    lottie: false
  assets:
    enabled: true
    outputs:
      style: dot-delimiter
      class_name: Assets

flutter_intl:
  enabled: true
  main_locale: th
  class_name: AppLocalizations
  arb_dir: lib/core/l10n
  output_dir: lib/core/l10n/generated

import_sorter:
  emojis: false
  comments: false