name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.10.0
  widgetbook_annotation: ^3.2.0
  flutter_quote_generator_v2:
    path: ../
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  widgetbook_generator: ^3.9.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  fonts:
    - family: ibmPlexSansThai
      fonts:
        - asset: ../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Thin.ttf
          weight: 100
        - asset: ../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-ExtraLight.ttf
          weight: 200
        - asset: ../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Light.ttf
          weight: 300
        - asset: ../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Regular.ttf
          weight: 400
        - asset: ../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Medium.ttf
          weight: 500
        - asset: ../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-SemiBold.ttf
          weight: 600
        - asset: ../assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Bold.ttf
          weight: 700
